from django.db import models

class TurboModel(models.Model):
      liczba_tlokow=models.IntegerField()
      cykl_pracy=models.CharField(max_length=3)
      objetosc_skokowa=models.FloatField()
      maksymalne_obroty_silnika=models.IntegerField()
      wspolczynnik_napelnienia=models.FloatField()
      moc_silnika=models.IntegerField()  
      sprawnosc_efektywna=models.IntegerField()       
      kappa=models.FloatField("Wspolczynnik politropy")
      etah=models.FloatField("Sprawnosc hydrauliczna")
      sprez=models.FloatField("Sprez")
      c1a=models.FloatField()
      P1t=models.IntegerField("Cisnienie spalin")
      T1t=models.IntegerField("Temperatura spalin")
      D1D2t=models.FloatField("Stosunek srednic")
      fit=models.FloatField("Wspolczynnik strat predkosci w konfuzorze")
      psit=models.FloatField("Wspolczynnik strat predkosci")
      beta2t=models.IntegerField("Kat lopatki wirnika turbiny")
      alpha2t=models.IntegerField("Kat wylotowyz dyfuzora")
#dodac do formulaza kappa,etah,sprez

class TurboResultModel(models.Model):
      strumien_masy_powietrza=models.FloatField("Strumien masy powietrza")
      praca_izentropowa=models.FloatField("Praca izentropowa")
      temperatura_w_przekroju_wejsciowym=models.FloatField("Temperatura w przekroju wejsciowym")
      predkosc_obwodowa=models.FloatField("Predkosc obwodowa")
      predkosc_wzgledna_na_wlocie=models.FloatField("Predkosc wzgleedna na wlocie ")
      u1=models.FloatField("Predkosc unoszenia na wlocie do sprezarki")
      P1=models.FloatField("Cisnienie na wlocie")
      beta1=models.FloatField("Kat wygiecia lopatki beta 1")
      mi=models.FloatField("Wspolczynnik mocy sprezarki")
      c2u=models.FloatField("Rzut pionowy predkosci bezwzglednej")
      c2=models.FloatField("Predosc wylotowa wirnika")
      w2=models.FloatField("Predkosc wzgledna na wylocie")
      beta2=models.FloatField("Kat na wylocie beta 2")
      T2=models.FloatField("Temperatura na wylocie z wirnika")
      p2=models.FloatField("cisnienie na wylocie z wirnika")
      A1=models.FloatField("Pole wlotowe wirnika")
      D2=models.FloatField("Srednica wylotowa wirnika")
      D1=models.FloatField("Srednca wlotowa do witnika")
      D0=models.FloatField("Srednica piasty na wlocie do wirnika")
      b=models.FloatField("szerokosc kanalu wlotowego")
      h1=models.FloatField("Wysokosc wirnika sprezarki")
      rp=models.FloatField("promien krzywizny piasty")
      D2_kr=models.FloatField("Srednica wylotowa z dyfuzora")
      c2_kr=models.FloatField("Predkosc czastek z dyfuzora")
      T2_kr=models.FloatField("Temp. czynnika z dyfuzora")
      P2_kr=models.FloatField("Wzrost cisnienia w dyfuzorze")
      T3=models.FloatField("Temp na wyjsciu z kolektora")
      p3=models.FloatField("Cisnienie na wylocie z kolektora")
      A3=models.FloatField("Pole kolektora na wylocie")
      n=models.FloatField("Predkosc obrotowa")
      ls=models.FloatField("Praca sprezarki")
      eta_s=models.FloatField("Sprawnosc sprezarki")
      Ns=models.FloatField("Moc napedu sprezarki")
      m_str_st=models.FloatField("Ilosc spalin opuszczajacych turbin")
      B_st=models.FloatField("Strumien paliwa")
      rhot=models.FloatField("Gestosc teoretyczna")
      Wt=models.FloatField("Wartosc opalowa paliwa")
      ntt=models.FloatField("Predkosc obrotowa turbiny")
      Ntt2=models.FloatField("Moc na wale turbiny")
      sprezt=models.FloatField("Sprez")
      lambda_izt=models.FloatField("Stosunek predkosci")
      tao=models.FloatField("Stosunek temperatur")
      a_kr1t=models.FloatField("Wlotowa predkosc krytyczna")
      c_izt=models.FloatField("Predkosc wyplywu spalin")
      u_2t=models.FloatField("Predkosc obwodowa na wlocie")
      u_3t=models.FloatField("Predkosc obwodowa na wylocie")
      c2t=models.FloatField("Rzeczywista predkosc zredukowana na wylocie z konfuzora")
      lambdac2t=models.FloatField("Rzeczywista predkosc teoretyczna na wylocie z konfuzora")
      T2t=models.FloatField("Temperatura za konfuzorem")
      P2t=models.FloatField("Cisnienie za konfuzorem")
      W2t=models.FloatField("Predkosc wzgledna za konfuzorem")
      T2_primrt=models.FloatField("Temperatura spietrzenia na wlocie do wirnika")
      P2_primrt=models.FloatField("Cisnienie spietrzenia na wlocie do wirnika")
      piwt=models.FloatField("Sprez na wirniku turbiny")
      w3t=models.FloatField("Predkosc wyplywu spalin z wirnika turbiny")
      Tprim3t=models.FloatField("Temperatura na wylocie z wirnika")
      akr3t=models.FloatField("Predkosc krytyczna na wylocie z wirnika turbiny")
      T2tt=models.FloatField("Rzeczywista temperatura za wirnikiem")
      C3tt=models.FloatField("Predkosc bezwzgledna na wylocie z wirnika")
      beta_1t=models.FloatField("Kat wygiecia lopatkiturbiny")
      D1t=models.FloatField("Srednica wlotowa wirnika")
      D2t=models.FloatField("Srednica wylotowa")
      D0t=models.FloatField("Srednica wylotowa piasty")
      h1t=models.FloatField("Wysokosc wirnika turbiny")
      rp1=models.FloatField("Promien krzywizny piasty")
      hw1=models.FloatField("Wysokosc kanalu wlotowego")
      zt=models.IntegerField("Lczba lopatek turbiny")
      rkwt=models.FloatField("Wewnetrzny promien konfuzora turbiny")
      rkzt=models.FloatField("Zewnetrzny promien")
      rszkt=models.FloatField("Promien lini szkieletowej")
      r0t=models.FloatField("Promien zaczepienia lini szkieletowej")
      




